//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simpleza.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simpleza.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _new {
            get {
                object obj = ResourceManager.GetObject("_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Compile {
            get {
                object obj = ResourceManager.GetObject("Compile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Cut {
            get {
                object obj = ResourceManager.GetObject("Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ejecutar {
            get {
                object obj = ResourceManager.GetObject("Ejecutar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap findreplace {
            get {
                object obj = ResourceManager.GetObject("findreplace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap left {
            get {
                object obj = ResourceManager.GetObject("left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap print {
            get {
                object obj = ResourceManager.GetObject("print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap redo {
            get {
                object obj = ResourceManager.GetObject("redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap right {
            get {
                object obj = ResourceManager.GetObject("right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de....
        /// </summary>
        public static string sAboutUs {
            get {
                return ResourceManager.GetString("sAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilar.
        /// </summary>
        public static string sCompile {
            get {
                return ResourceManager.GetString("sCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar.
        /// </summary>
        public static string sCopy {
            get {
                return ResourceManager.GetString("sCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cortar.
        /// </summary>
        public static string sCut {
            get {
                return ResourceManager.GetString("sCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutar.
        /// </summary>
        public static string sEjecutar {
            get {
                return ResourceManager.GetString("sEjecutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string sExit {
            get {
                return ResourceManager.GetString("sExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar....
        /// </summary>
        public static string sFind {
            get {
                return ResourceManager.GetString("sFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar siguiente (F3).
        /// </summary>
        public static string sFindNext {
            get {
                return ResourceManager.GetString("sFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar anterior (SHIFT+F3).
        /// </summary>
        public static string sFindPrevious {
            get {
                return ResourceManager.GetString("sFindPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda.
        /// </summary>
        public static string sHelp {
            get {
                return ResourceManager.GetString("sHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SimplezaLogo {
            get {
                object obj = ResourceManager.GetObject("SimplezaLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coincidir mayúsculas/minúsculas.
        /// </summary>
        public static string sMatchCase {
            get {
                return ResourceManager.GetString("sMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string sNew {
            get {
                return ResourceManager.GetString("sNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir....
        /// </summary>
        public static string sOpen {
            get {
                return ResourceManager.GetString("sOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pegar.
        /// </summary>
        public static string sPegar {
            get {
                return ResourceManager.GetString("sPegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir....
        /// </summary>
        public static string sPrint {
            get {
                return ResourceManager.GetString("sPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rehacer.
        /// </summary>
        public static string sRedo {
            get {
                return ResourceManager.GetString("sRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reemplazar....
        /// </summary>
        public static string sReplace {
            get {
                return ResourceManager.GetString("sReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string sSave {
            get {
                return ResourceManager.GetString("sSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar como....
        /// </summary>
        public static string sSaveAs {
            get {
                return ResourceManager.GetString("sSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleZa GarGar ADI.
        /// </summary>
        public static string sTitulo {
            get {
                return ResourceManager.GetString("sTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        public static string sTooltipAboutUs {
            get {
                return ResourceManager.GetString("sTooltipAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilar.
        /// </summary>
        public static string sTooltipCompile {
            get {
                return ResourceManager.GetString("sTooltipCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar.
        /// </summary>
        public static string sTooltipCopy {
            get {
                return ResourceManager.GetString("sTooltipCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cortar.
        /// </summary>
        public static string sTooltipCut {
            get {
                return ResourceManager.GetString("sTooltipCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutar.
        /// </summary>
        public static string sTooltipEjecutar {
            get {
                return ResourceManager.GetString("sTooltipEjecutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string sTooltipExit {
            get {
                return ResourceManager.GetString("sTooltipExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string sTooltipFind {
            get {
                return ResourceManager.GetString("sTooltipFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda.
        /// </summary>
        public static string sTooltipHelp {
            get {
                return ResourceManager.GetString("sTooltipHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string sTooltipNew {
            get {
                return ResourceManager.GetString("sTooltipNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        public static string sTooltipOpen {
            get {
                return ResourceManager.GetString("sTooltipOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pegar.
        /// </summary>
        public static string sTooltipPegar {
            get {
                return ResourceManager.GetString("sTooltipPegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        public static string sTooltipPrint {
            get {
                return ResourceManager.GetString("sTooltipPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rehacer.
        /// </summary>
        public static string sTooltipRedo {
            get {
                return ResourceManager.GetString("sTooltipRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reemplazar.
        /// </summary>
        public static string sTooltipReplace {
            get {
                return ResourceManager.GetString("sTooltipReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string sTooltipSave {
            get {
                return ResourceManager.GetString("sTooltipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar como.
        /// </summary>
        public static string sTooltipSaveAs {
            get {
                return ResourceManager.GetString("sTooltipSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deshacer.
        /// </summary>
        public static string sTooltipUndo {
            get {
                return ResourceManager.GetString("sTooltipUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deshacer.
        /// </summary>
        public static string sUndo {
            get {
                return ResourceManager.GetString("sUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usar expresiones regulares.
        /// </summary>
        public static string sUsarExpresionesRegulares {
            get {
                return ResourceManager.GetString("sUsarExpresionesRegulares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar palabras completas.
        /// </summary>
        public static string sWholeWords {
            get {
                return ResourceManager.GetString("sWholeWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
